### ISSUE TITLE
steam _find_info fails when the keys are in lowercase

### ISSUE THREAD

**Issue by sandiz** [BuongiornoTexas/rsrtools#12]
hi @BuongiornoTexas , 

looks like the keys in `config/loginusers.vdf` are not guaranteed to be in camel case
eg: 
```"users"
{
	<# removed in case it's sensitive> 
	{
		"accountname"		"#"
		"PersonaName"		"JustinAiken"
		"RememberPassword"		"1"
		"Timestamp"		"1556751550"
		"WantsOfflineMode"		"0"
		"SkipOfflineModeWarning"		"0"
		"mostrecent"		"1"
	}
}
```
stack trace
```python
Traceback (most recent call last):
  File "/usr/local/bin/importrsm", line 6, in <module>
    from rsrtools.importrsm import main
  File "/usr/local/lib/python3.7/site-packages/rsrtools/importrsm.py", line 21, in <module>
    from rsrtools.songlists.database import ArrangementDB
  File "/usr/local/lib/python3.7/site-packages/rsrtools/songlists/database.py", line 40, in <module>
    from rsrtools.files.profilemanager import RSProfileManager, JSON_path_type
  File "/usr/local/lib/python3.7/site-packages/rsrtools/files/profilemanager.py", line 1016, in <module>
    class RSProfileManager:
  File "/usr/local/lib/python3.7/site-packages/rsrtools/files/profilemanager.py", line 1100, in RSProfileManager
    _steam_accounts: SteamAccounts = SteamAccounts()
  File "/usr/local/lib/python3.7/site-packages/rsrtools/files/steam.py", line 191, in __init__
    self._account_info = self._find_info()
  File "/usr/local/lib/python3.7/site-packages/rsrtools/files/steam.py", line 263, in _find_info
    name = login_info["AccountName"]
KeyError: 'AccountName'
```

cc @JustinAiken, more info in https://github.com/sandiz/rs-manager/issues/58#issuecomment-489213328

**Comment by BuongiornoTexas** [comment]
Closed in [0.2.1](https://github.com/BuongiornoTexas/rsrtools/releases/tag/0.2.1beta).
